FROM python:3.12-slim

ARG SJP_VERSION=0.1.1
WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ADD https://github.com/Tikhovskoy/StaticJinjaPlus/archive/refs/tags/v${SJP_VERSION}.tar.gz /app/sjp.tar.gz

RUN tar -xzf sjp.tar.gz && \
    mv StaticJinjaPlus-* StaticJinjaPlus && \
    rm sjp.tar.gz

WORKDIR /app/StaticJinjaPlus

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

ENTRYPOINT ["python", "main.py"]
